# Generate a snake eating your contributions.

name: github-contribution-grid-snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        
      - name: ğŸ”¨ generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: ./src/github-contribution-grid-snake.svg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: ğŸš— Push to GitHub
        uses: EndBug/add-and-commit@v7.2.1
        with:
          branch: master
          message: 'ğŸ SNAKE IS CRAWLING!!!'
